<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
        <Nullable>enable</Nullable>
        <RootNamespace>OddWire</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="0Harmony">
          <HintPath>..\..\..\..\Users\eagle\AppData\Roaming\Vintagestory\Lib\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="cairo-sharp">
          <HintPath>..\..\..\..\Users\eagle\AppData\Roaming\Vintagestory\Lib\cairo-sharp.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json">
          <HintPath>..\..\..\..\Users\eagle\AppData\Roaming\Vintagestory\Lib\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="Vintagestory">
          <HintPath>..\..\..\..\Users\eagle\AppData\Roaming\Vintagestory\Vintagestory.dll</HintPath>
        </Reference>
        <Reference Include="VintagestoryAPI">
            <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="VSSurvivalMod">
            <HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="VSEssentials">
            <HintPath>$(VINTAGE_STORY)/Mods/VSEssentials.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="VSCreativeMod">
            <HintPath>$(VINTAGE_STORY)/Mods/VSCreativeMod.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="VintagestoryLib">
            <HintPath>$(VINTAGE_STORY)/VintagestoryLib.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Content Include=".ai\*" />
        <Content Include="modinfo.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Content Include="modicon.png" Condition="Exists('modicon.png')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
